version: '3.7'

services:

  films_table:
    container_name: films_table
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/films_table'
      - '/films_table/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
